// <auto-generated />
namespace R2.RRDL.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddContactPersons : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddContactPersons));
        
        string IMigrationMetadata.Id
        {
            get { return "201404300308224_AddContactPersons"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
